export const REPO_DETAIL_FETCH = 'REPO_DETAIL_FETCH';
export const REPO_DETAIL_FETCH_SUCCESS = 'REPO_DETAIL_FETCH_SUCCESS';

export const CONTRIBUTORS_FETCH = 'CONTRIBUTORS_FETCH';
export const CONTRIBUTORS_FETCH_SUCCESS = 'CONTRIBUTORS_FETCH_SUCCESS';
